modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Custom"

[[mods]]
modId = "safaribanquet"
version = "${version}"
displayName = "Safari Banquet"
authors = "satisfy"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.safaribanquet]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.safaribanquet]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.safaribanquet]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"